[package]
name = "dep1"
version = "0.1.0"
edition = "2021"
description = "dependencies test"
repository = "git@github.com:ohadApiiro/dep1.git"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
